---
apiVersion: v1
kind: Pod
metadata:
  name: build-pod
spec:
  containers:
    - name: build-worker
      image: {{ images['docker-builder'] }}
      command: ["/bin/sh"]
      args: ["-c", "buildbot-worker create-worker . ${BUILDMASTER}:${BUILDMASTER_PORT} ${WORKERNAME} ${WORKERPASS} && buildbot-worker start --nodaemon"]
      resources:
        requests:
          cpu: 500m
          memory: 1Gi
        limits:
          cpu: 500m
          memory: 1Gi
      env:
        - name: DOCKER_HOST
          value: localhost
      volumeMounts:
        - name: worker-workspace
          mountPath: /home/eve/workspace
    - name: platform-dind-daemon
      image: docker:18.09.2-dind
      resources:
        requests:
          cpu: "1"
          memory: 2Gi
        limits:
          cpu: "2"
          memory: 2Gi
      securityContext:
        privileged: true
      volumeMounts:
        - name: docker-storage
          mountPath: /var/lib/docker
        - name: worker-workspace
          mountPath: /home/eve/workspace
  volumes:
    # The two volumes below are used to avoid intensive IO in the Docker overlay
    # If extra performance is required, one could add `medium: Memory` to the
    # `emptyDir` dicts.
    # See https://docs.docker.com/storage/volumes/
    - name: docker-storage
      emptyDir: {}
    - name: worker-workspace
      emptyDir: {}
